name: PR Gatekeeper

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: Git ref to test
      services:
        type: string
        description: Comma-separated list of services

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Message ${{ toJSON(github.event) }}"
          echo "Rishant Testing - Caller Workflow"
          printenv
          export DOCKER_TAG_GIT_COMMIT_ID=$(git rev-parse HEAD)
          echo $DOCKER_TAG_GIT_COMMIT_ID
          export DOCKER_TAG_VERSION_GIT_COMMIT_ID=$(date +%Y.%m.%d)
          echo $DOCKER_TAG_VERSION_GIT_COMMIT_ID
  reuseable:
    needs: [print]
    uses: ./.github/workflows/reuseable_workflow.yaml
    secrets: inherit
    with:
      mode: "testing"
      business-unit: "IN"
    
