name: PR Gatekeeper

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: Git ref to test
      services:
        type: string
        description: Comma-separated list of services

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Print Inputs
        run: |
          echo "Message ${{ toJSON(github.event) }}"
