name: PR Gatekeeper

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: Git ref to test
      services:
        type: string
        description: Comma-separated list of services

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Message ${{ toJSON(github.event) }}"
          echo "Rishant Testing - Caller Workflow"
          printenv
          # export DOCKER_TAG_GIT_COMMIT_ID=$(git rev-parse HEAD)
          # export DOCKER_TAG_VERSION_GIT_COMMIT_ID=$(date +%Y.%m.%d)          
          echo "DOCKER_TAG_GIT_COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV;
          echo "DOCKER_TAG_VERSION_GIT_COMMIT_ID=$(date +%Y.%m.%d)" >> $GITHUB_ENV;
          echo $DOCKER_TAG_GIT_COMMIT_ID
          echo $DOCKER_TAG_VERSION_GIT_COMMIT_ID
          env_vars=$(env | grep -v '^GITHUB_' | jq -n 'reduce inputs as $in ({}; setpath([$in | split("=") | first]; ($in | split("=") | last)))')
          echo "ENV_JSON=$env_vars" >> $GITHUB_ENV
  reuseable:
    needs: [print]
    uses: ./.github/workflows/reuseable_workflow.yaml
    secrets: inherit
    with:
      mode: "testing"
      business-unit: "IN"
      env_json: ${{ needs.print.env.ENV_JSON || print.ENV_JSON}}
    
