name: Print Action Runner Contexts

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  print_contexts:
    runs-on: ubuntu-latest  # Or any runner you prefer

    steps:
      - name: Print github context
        run: echo '${{ toJSON(github) }}'

      - name: Print env context
        run: echo '${{ toJSON(env) }}'

      - name: Print vars context
        run: echo '${{ toJSON(vars) }}'

      - name: Print job context
        run: echo '${{ toJSON(job) }}'

      # - name: Print jobs context
      #   run: echo '${{ toJSON(jobs) }}'

      - name: Print steps context
        run: echo '${{ toJSON(steps) }}'

      - name: Print runner context
        run: echo '${{ toJSON(runner) }}'

      - name: Print secrets context
        run: echo '${{ toJSON(secrets) }}'

      - name: Print strategy context
        run: echo '${{ toJSON(strategy) }}'

      - name: Print matrix context
        run: echo '${{ toJSON(matrix) }}'

      - name: Print needs context
        run: echo '${{ toJSON(needs) }}'

      - name: Print inputs context
        run: echo '${{ toJSON(inputs) }}'
